# Generated by Django 4.2.20 on 2025-04-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='ssid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
