# Generated by Django 4.2.20 on 2025-05-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0003_systemlog_lightzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightzone',
            name='esp_address',
            field=models.GenericIPAddressField(default=0, protocol='IPv4'),
        ),
    ]
