# Generated by Django 4.2.20 on 2025-05-14 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parks', '0004_lightzone_esp_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightzone',
            name='esp_address',
        ),
        migrations.CreateModel(
            name='ESP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lightzone',
            name='esp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='parks.esp'),
        ),
    ]
